from django.conf.urls import  url
from web_MA_DB import views

urlpatterns = [
    url(r'^$',views.index,name ='index'),
    url(r'^homepage/$',views.homepage,name='homepage'),
	# url(r'^$', views.index, name='index'),
	url(r'^node/(?P<node_name_slug>[\w\-]+)/$',views.node, name='node'),
	url(r'^(?P<node_name_slug>[\w\-]+)/in_node_results',views.in_node_results,name = 'in_node_results'),
	url(r'^(?P<node_name_slug>[\w\-]+)/add_project/$',views.add_project,name = 'add_project'),
	url(r'^(?P<node_name_slug>[\w\-]+)/projects_list/$',views.projects_list, name ='projects_list'),
	url(r'^add_project/$',views.index,name='add_finish'),
	url(r'^(?P<node_name_slug>[\w\-]+)/node_chart/$',views.node_chart,name ='node_chart'),
	url(r'^(?P<pro_id>[0-9]*)/project_detail/$',views.project_detail,name ='project_detail'),
	url(r'^client_volume/$',views.client_volume,name='client_volume'),
	url(r'^fund_chart/$',views.fund_chart,name='fund_chart'),
	url(r'^invoice_number/$',views.invoice_number,name='invoice_number'),
	url(r'^MA_search/$',views.MA_search,name = 'MA_search'),
	url(R'^MA_search_results/$',views.MA_search_results,name='MA_search_results'),
	url(r'^detail_search/$',views.detail_search,name='detail_search'),
	url(r'^detail_search_results/$',views.detail_search_results,name ='detail_search_results'),
	url(r'^um_reconcil_search/$',views.um_reconcil_search,name ='um_reconcil_search'),
	url(r'^um_reconcil_results/$',views.um_reconcil_results,name ='um_reconcil_results'),
	url(r'^node_search/$',views.node_search,name ='node_search'),
	url(r'^node_search_results/$',views.node_search_results,name ='node_search_results'),
	url(r'^state_search/$',views.state_search,name = 'state_search'),
	url(r'^state_search_result/$',views.state_search_result,name='state_search_result'),
	url(r'^field_search/$',views.field_search,name = 'field_search'),
	url(r'^field_search_results/$',views.field_search_results,name='field_search_results'),	
	url(r'^type_search/$',views.type_search,name = 'type_search'),
	url(r'^type_search_results/$',views.type_search_results,name='type_search_results'),
	url(r'^int_ext_search/$',views.int_ext_search,name = 'int_ext_search'),
	url(r'^int_ext_results/$',views.int_ext_results,name='int_ext_results'),
	url(r'^import_quotes/$',views.readQuoteSheet,name ='read_quote_sheet'),
	url(r'^usertype_income/$',views.usertype_income,name='usertype_income'),
	url(r'^nodes_year_search/$',views.nodes_year_search,name='nodes_year_search'),
	url(r'^nodes_year_column/$',views.nodes_year_column,name = 'nodes_year_column'),
	url(r'^cat_year_search/$',views.cat_year_search,name='cat_year_search'),
	url(r'^cat_year_column/$',views.cat_year_column,name = 'cat_year_column'),
	url(r'^register/$',views.register, name='register'),
	url(r'^login/$',views.admin_login,name='login'),
	url(r'^logout/$',views.admin_logout,name="logout"),
	url(r'^blank/$',views.blank,name='blank'),
	url(r'^upload/$',views.readProjectSheet,name='upload'),
	url(r'^import_invoice/$',views.readInvoiceSheet,name='import_invoice'),
	url(r'^update_field/$',views.update_field,name = 'update_field'),
	url(r'^update_type/$',views.update_type,name = 'update_type'),
]

	