# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=45)),
                ('node_area', models.CharField(max_length=45)),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Node',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('org_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('service', models.CharField(blank=True, max_length=45, null=True)),
                ('instrument', models.CharField(blank=True, max_length=45, null=True)),
                ('person', models.CharField(blank=True, max_length=45, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('num_sample', models.IntegerField(blank=True, null=True)),
                ('int_ext', models.CharField(blank=True, max_length=3, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, max_length=11, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cus_count', models.CharField(blank=True, max_length=1, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_MA_DB.Category')),
                ('node', models.ForeignKey(blank=True, db_column='node', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_MA_DB.Node')),
            ],
            options={
                'db_table': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userfield',
            fields=[
                ('field_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'UserField',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('type_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'UserType',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='userfield',
            field=models.ForeignKey(blank=True, db_column='userfield', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_MA_DB.Userfield'),
        ),
        migrations.AddField(
            model_name='project',
            name='usertype',
            field=models.ForeignKey(blank=True, db_column='usertype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_MA_DB.Usertype'),
        ),
    ]
