# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_MA_DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userfield',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'managed': False},
        ),
    ]
