# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_MA_DB', '0003_projectsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsheet',
            options={'managed': False},
        ),
    ]
