# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MA_DB', '0006_auto_20161010_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to='')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
